---
name: Test

on:
  workflow_dispatch:

jobs:
  Linux:
    strategy:
      fail-fast: false
      #matrix:
        #volume:
          #- /tmp
          #- .
          #- relative-path
          #- /
        #asroot:
         # - name: ''
          #  sudo: ''
         # - name: ' as root'
          #  sudo: 'sudo '

    name: Linux ${{ matrix.volume }}${{ matrix.asroot.name }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y libparted-dev libudev-dev
      - run: make -f Makefile.linux all extra -j42069

#      - if: matrix.volume == 'relative-path'
 #       run: mkdir relative-path

  #    - if: matrix.volume == '/'
   #     run: sudo chmod a+w /

    #  - run: ./f3write -V
     # - run: ./f3write --help
     # - run: ${{ matrix.asroot.sudo }}./f3write -s 2 -e 4 -w 50000 ${{ matrix.volume }}

 #     - run: stat ${{ matrix.volume }}/2.h2w
  #    - run: stat ${{ matrix.volume }}/3.h2w
   #   - run: stat ${{ matrix.volume }}/4.h2w

    #  - run: ./f3read -V
     # - run: ./f3read --help
      #- run: ${{ matrix.asroot.sudo }}./f3read -s 2 -e 4 -r 50000 ${{ matrix.volume }}


      - run: |
          make all extra -j42069

      - name: Linux BUILD
        uses: actions/upload-artifact@v4.1.0
        with: 
          name: Linux f3 BUILD
          path: ./f3*

  MacOS:
    strategy:
      fail-fast: false
      #matrix:
      #  volume:
      #    - /tmp
      #    - .
      #    - relative-path
          # MacOS denies `sudo chmod a+w /`
          #- /
      #  asroot:
      #    - name: ''
      #      sudo: ''
      #    - name: ' as root'
      #      sudo: 'sudo '

    name: MacOS ${{ matrix.volume }}${{ matrix.asroot.name }}
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - run: brew install argp-standalone build-essential git cmake ninja-build libudev-dev gcc-6 g++-6
      - run: make 

      #- if: matrix.volume == 'relative-path'
      #  run: mkdir relative-path

      #- run: ./f3write -V
      #- run: ./f3write --help
      #- run: ${{ matrix.asroot.sudo }}./f3write -s 2 -e 4 -w 50000 ${{ matrix.volume }}

      #- run: stat ${{ matrix.volume }}/2.h2w
      #- run: stat ${{ matrix.volume }}/3.h2w
      #- run: stat ${{ matrix.volume }}/4.h2w

      #- run: ./f3read -V
      #- run: ./f3read --help
      #- run: ${{ matrix.asroot.sudo }}./f3read -s 2 -e 4 -r 50000 ${{ matrix.volume }}

      - run: |
          git clone --recursive https://github.com/therealkenc/libudev-stub.git libudev
          ./scripts/build-all.sh
          make all extra -j42069

      - name: Mac BUILD
        uses: actions/upload-artifact@v4.1.0
        with:
          name: MacOS f3 BUILD
          path: ./f3*

  Cygwin:
    strategy:
      fail-fast: false
      #matrix:
      #  volume:
      #    - cygwin: /cygdrive/c
      #      windows: 'C:'
      #    - cygwin: .
      #      windows: .
      #    - cygwin: relative-path
      #      windows: relative-path
      #    - cygwin: /
      #      windows: 'C:\cygwin'

    name: Cygwin ${{ matrix.volume.cygwin }}
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - uses: cygwin/cygwin-install-action@v2
        with:
          packages: gcc-core libargp-devel make build-essential git cmake ninja-build libudev-dev gcc-6 g++-6
          
      - run: "$Env:LDFLAGS = '-Wl,--stack,4000000'; make"

     # - if: matrix.volume.windows == 'relative-path'
      #  run: New-Item -ItemType Directory -Path relative-path

     # - run: '& .\f3write.exe -V'
     # - run: '& .\f3write.exe --help'
     # - run: '& .\f3write.exe -s 2 -e 4 -w 50000 ${{ matrix.volume.cygwin }}'

    #  - run: 'Get-Item ${{ matrix.volume.windows }}\2.h2w'
   #   - run: 'Get-Item ${{ matrix.volume.windows }}\3.h2w'
      #- run: 'Get-Item ${{ matrix.volume.windows }}\4.h2w'

      #- run: '& .\f3read.exe -V'
     # - run: '& .\f3read.exe --help'
      #- run: '& .\f3read.exe -s 2 -e 4 -r 50000 ${{ matrix.volume.cygwin }}'

      - run: |
          git clone --recursive https://github.com/therealkenc/libudev-stub.git libudev
          cd libudev
          bash ./scripts/build-all.sh
          make all extra -j42069
        
      - name: Windows BUILD
        uses: actions/upload-artifact@v4.1.0
        with: 
          name: Windows f3 BUILD
          path: ./f3*
